#!/bin/bash

# Set XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"

# Create symlinks
ln -sf "$PWD/bash/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/bash/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME/nvim"
ln -sf "$PWD/starship" "$XDG_CONFIG_HOME/starship"
ln -sf "$PWD/lazygit" "$XDG_CONFIG_HOME/lazygit"
ln -sf "$PWD/tmux/tmux.conf" "$HOME/.tmux.conf"

# install packages with brew 
packages=(
  bat  
  fd  
  tmux
  ripgrep
  starship
  npm
  lazygit
  fzf
  kubectl
  k9s
  direnv
  kubectx
)

# install each package from array
for package in "${packages[@]}"; do
  echo "installing $package..."
  /home/linuxbrew/.linuxbrew/bin/brew install "$package"
done
