# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[](white)"
error_symbol = "[](red)"

[directory]
style = "blue bold"
home_symbol = "~"

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[docker_context]
disabled = true

[git_branch]
disabled = false

[git_commit]
disabled = true

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "C"
untracked = "U"
modified = "M"
renamed = "R"
staged = "S"
deleted = "D"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = true

[cmd_duration]
disabled = true
