[tools]

neovim = "latest"
ripgrep = "latest"
bat = "latest"
btop = "latest"
fzf = "latest"
node = "latest"
usage = "latest"    # for mise completion
starship = "latest"
chezmoi = "latest"
lazygit = "latest"
fd = "latest"
