git:
  showIcons: true

paging:
  useConfig: true

os:
  editPreset: "nvim"

customCommands:
  - key: "P"
    command: "git pull --rebase --autostash && git push"
    description: "Pull (rebase) then push"
    context: "global"
    loadingText: "pulling and pushing..."
    stream: true
    showOutput: true
